### ISSUE TITLE
Probable reason why the increment api is not found.

### ISSUE THREAD

**Issue by GoodBoiDoggo** [thereserayza/catalog-service#1]
Not sure, but just an observation. All of the @GetMapping's in the catalog dont have the string "value=" at the start, EXCEPT this non functioning api link. Since its a get request it would also be safe to return at least a string(for example: 
```java
return "View succesfully incremented";
```
The defected API link:
```java	
	@GetMapping(value="/item/view/{prodcode}") //<---See here
	public void incrementViewCount(@PathVariable String prodcode) {
		Query query = new Query().addCriteria(Criteria.where("prodcode").is(prodcode));
		Update update = new Update().inc("viewcount", 1);
		mongoTemplate.updateFirst(query, update, "catalogdata");
	}
```

**Comment by thereserayza** [comment]
If there are no other attributes that need to be mentioned in any RequestMapping, "value=" is not necessary since it is like a default attribute.

**Comment by GoodBoiDoggo** [comment]
Ok. But please add a return string and also try to remove the "value=" part. If it doesn't return the string or work, then it only means the Mapping path is the problem

**Comment by thereserayza** [comment]
Removing the "value=" doesn't change anything. Will check if returning does anything.

**Comment by thereserayza** [comment]
I still think that using PUT would be a better option.

**Comment by GoodBoiDoggo** [comment]
I think its another mapping path problem.
```java
      @GetMapping("/item/{prodcode}/discount")
	public double getDiscountPrice(@PathVariable String prodcode) {
		Query query = new Query().addCriteria(Criteria.where("prodcode").is(prodcode));
		Catalog _catalog = mongoTemplate.findOne(query, Catalog.class, "catalogdata");
		double discountedPrice = _catalog.getProdprice() * (1 - _catalog.getDiscountrate());
		return discountedPrice;
	}
	
	@GetMapping(value="/item/view/{prodcode}")
	public void incrementViewCount(@PathVariable String prodcode) {
		Query query = new Query().addCriteria(Criteria.where("prodcode").is(prodcode));
		Update update = new Update().inc("viewcount", 1);
		mongoTemplate.updateFirst(query, update, "catalogdata");
	}
```
I believe that changing the path for getDiscount from
"/item/{prodcode}/discount" to
"/item/discount/{prodcode}"
or making it a "putMapping" could solve the path problem

**Comment by GoodBoiDoggo** [comment]
When converting the API link put, Please set the Content-Length to 0, so that it will expect no body.

**Comment by GoodBoiDoggo** [comment]
PLease do

**Comment by thereserayza** [comment]
The reason why any of the solutions we did was that the package I sent wasn't the updated one.
Since this is a Maven project using spring-boot, every update should be "mvn clean package" before pushing it for deployment.
